echo-container-chart:
  imageTag: latest
  image:
    name: echo_container
    pullPolicy: IfNotPresent

  resources:
    requests:
      memory: 100Mi
      cpu: 0.2
    limits:
      memory: 200Gi
      cpu: 0.4

  autoscaling:
    minReplicas: 2
    maxReplicas: 4

  service:
    type: NodePort
    service_port: 4747
    ingress_port: 80

  ingress:
    ingressClassName: "ingress-nginx"
    domain: ""

  podDisruptionBudget:
    enabled: true