apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.ingress.domain | trunc 63 | replace "." "-" | replace "*" "wildcard" }}
  labels:
    app: {{.Release.Name}}
    chart: {{ .Chart.Name}}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: {{ required "Domain for ingress is required" (.Values.ingress.domain) }}
      http:
        paths:
          - backend:
              serviceName: {{.Release.Name}}
              servicePort: {{ .Values.service.service_port }}
            path: /