apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.domain | trunc 63 | replace "." "-" | replace "*" "wildcard" }}
  labels:
    app: {{.Release.Name}}
    chart: {{ .Chart.Name}}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1    
spec:
  rules:
  - host: {{ required "Domain for ingress is required" (.Values.ingress.domain) }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: {{.Release.Name}}
            port:
              number: {{ .Values.service.ingress_port }}